mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings 
from django.conf.urls.static import static
from django.views.static import serve
urlpatterns = [
	url(r'^user/', include('personal_management.urls')),	#redirected to user page
	url(r'^manager/', include('manager.urls')),
	url(r'^result/', include('act_result.urls')),
    url(r'^admin/', admin.site.urls),
	url(r'^welcome/', include('start.urls')),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT})
]
'''
if settings.DEBUG is False:
    urlpatterns += patterns('', url(r'^static/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.STATIC_ROOT, }), )
'''

mysite/personal_management/urls.py
from django.conf.urls import url
from . import views

app_name = 'personal_management'
urlpatterns = [
	url(r'^fake_log_in$', views.fake_log_in, name = 'f_log_in'),
	url(r'^fake_log_out$', views.fake_log_out, name = 'f_log_out'),
	url(r'^list_page/(?P<content>applied|unapplied|applying)/$',\
	views.list_page , name = 'list_page'),
	url(r'^search/(?P<type>time|place|name)$', views.search, name = 'search'),
	url(r'^activity_detail/(?P<id>[0-9]+)$', views.detail, name = 'detail'),
	url(r'^edit_processor/(?P<id>[0-9]+)$', views.processor, name = 'processor'),
	url(r'^widthdraw$', views.withdraw, name = 'withdraw'),
	url(r'^apply$', views.apply, name = 'apply'),
	url(r'^create/(?P<type>manual|upload)', views.load, name = 'create'),
	url(r'^refresh/$', views.profile_refresh, name = 'refresh'),
	url(r'^log_out/$', views.my_log_out, name = 'log_out'),
]

mysite/start/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.start, name = 'start'),
	url(r'^help$', views.help, name = 'help'),
]

mysite/personal_management/forms.py
# -*- coding:utf-8 -*-  
from django import forms
import custom_proj.basic.models as c_b_models
class ActivityForm(forms.Form):
	name = forms.CharField(label = '活动名称', max_length = 256)
	time_start = forms.DateTimeField(label = '起始时间',input_formats = ['%Y-%m-%d %H'])
	time_end = forms.DateTimeField(label = '结束时间', input_formats = ['%Y-%m-%d %H'])
	num_participants = forms.IntegerField(label = '参与人数', min_value = 1)
	place = forms.CharField(label = '地点', max_length = 256)

class PrivilegeForm(forms.Form):
	privilege = forms.ChoiceField(label = '地点', choices = c_b_models.CHOICE_PRIVILEGE)

mysite/personal_management/views.py
# -*- coding:utf-8 -*-  
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from . import forms
import custom_proj.basic.models as custom_model
import datetime
import re
from django.db.models import Q
from custom_proj import links
#for development
from django.contrib.auth import authenticate, login, logout
from . import database_init as db_init

#only used for development
def fake_log_in(request):
	name = db_init.TEMP_USER_NAME
	passwd = db_init.TEMP_USER_PASSWORD
	user = authenticate(request, username = name, password = passwd)
	if user is not None:
		login(request, user)
		return HttpResponseRedirect(reverse('personal_management:refresh'))
	else:
		raise Http404('fake user does not exist')

def fake_log_out(request):
	logout(request)
	raise Http404('log_out')

def my_log_out(request):
	logout(request)
	return HttpResponseRedirect(reverse('start'))

NUM_ACT_PER_PAGE = 3

@login_required 
def list_page(request, **args):
	content = args['content']
	#index_current = args['index']
	dic_index = {'unapplied':0, 'applying':1, 'applied':2}
	dic_tmp = {'unapplied':0, 'applying':1, 'applied':2}		#used to configer string and consts in basic.models
	dic_lst_name = {'unapplied': '未申请', 'applying':'正在申请','applied':'已申请'}
	activity_list = custom_model.Activity.objects.filter(user = request.user, state = dic_tmp[content]).order_by('time_start')
	return render(request, 'personal_management/list_page.html',\
	 {'index':dic_index[content], 'activity_list':enumerate(activity_list),\
	 'page_size':'2', 'username':request.user.username, 'type_activity':dic_lst_name[content]})

def profile_refresh(request, **args):
	act_past = custom_model.Activity.objects.filter(user = request.user,
	 state = custom_model.APPLIED, time_start__lt = datetime.datetime.now())
	for act in act_past:
		act.delete()
	return HttpResponseRedirect(reverse('personal_management:list_page', args = ('unapplied',)))

@login_required
def search(request, **args):
	type_search = args['type']
	dic_tmp = {'is_inintial':True, 'type':type_search, \
			'fedback':reverse('personal_management:search', args = (type_search,)),\
			'page_dir':3, 'username':request.user.username}
	if request.method == 'POST':
		#用户提交了相应的搜索请求
		if type_search == 'time':
			#time的合法性检查
			t_s = check_time(request.POST['time_start'], '%Y/%m/%d')
			t_e = check_time(request.POST['time_end'], '%Y/%m/%d')
			if t_s == None or t_e == None:
				messages.info(request, '请按提示的格式输入时间')
				return HttpResponseRedirect(reverse('personal_management:search', args = ('time', )))
			t_e = t_e + datetime.timedelta(days = 1)
			result_list = custom_model.Activity.objects.filter(time_start__range = (t_s, t_e), user = request.user).order_by('time_start')
		elif type_search == 'place':
			place = check_place(request.POST['place'])
			if place == None:
				messages.info(request, '您输入的场地不存在')
				return HttpResponseRedirect(reverse('personal_management:search', args = ('place', )))
			result_list = custom_model.Activity.objects.filter(place = place, user = request.user)
		elif type_search == 'name':
			name = request.POST['name']
			result_list = custom_model.Activity.objects.filter(name__contains = name, user = request.user)
		else:
			return HttpResponseRedirect(reverse('personal_management:search', args = ('time', )))
		dic_tmp['is_initial'] = False
		dic_tmp['result'] = result_list
		return render(request, 'personal_management/search_page.html',dic_tmp)
	else:
		#用户初次来到该页面
		return render(request, 'personal_management/search_page.html',dic_tmp)		

@login_required
def detail(request, **args):
	try: act = custom_model.Activity.objects.get(id = args['id'], user = request.user)
	except ObjectDoesNotExist:
		raise Http404('您所访问的活动不存在')
	else:
		initial_data_act = {'name':act.name, 'time_start':act.time_start, \
		'time_end':act.time_end, 'num_participants':act.num_participants,\
		'place':act.place.name}
		f_act = forms.ActivityForm(initial_data_act, initial = initial_data_act)
		init_d_p = {'privilege':act.privilege}
		f_privilege = forms.PrivilegeForm(init_d_p, initial = init_d_p)
		pri_map = {'unapplied':custom_model.UNAPPLIED, 'applying':custom_model.APPLYING, 'applied':custom_model.APPLIED}
		lst_p = get_privilege_info(request.user)
		return render(request, 'personal_management/activity_detail.html',\
			{'f_act':f_act, 'f_privilege':f_privilege, 'state':act.state,\
			'activity':act, 'map_privilege':pri_map, 'privilege':act.privilege,
			'privilege_info': lst_p, 'privilege_bound':list(custom_model.NUM_PRIVILEGES),
			'username':request.user.username})

#如果不是申请活动，只要保证输入信息的基本合法性即可
#对于申请活动的情形，还需要保证活动没有冲突
@login_required
def processor(request, **args):
	if request.method == 'POST':
		act = get_object_or_404(custom_model.Activity, id = args['id'], user = request.user)
		if 'delete' in request.POST:
			act.delete()
			dic_state = {custom_model.UNAPPLIED:'unapplied', custom_model.APPLYING: 'applying', 
			custom_model.APPLIED: 'applied'}
			messages.info(request, '活动\"%s\"删除成功'%(act.name))
			return HttpResponseRedirect(reverse('personal_management:list_page', args = (dic_state[act.state],)))
		if act.state != custom_model.UNAPPLIED:
			if 'withdraw' in request.POST:
				#用户修改了申请情况,返回活动详情界面，并提示添加成功
				messages.info(request, '活动安排已取消')
				act.state = custom_model.UNAPPLIED
				act.save();
				return HttpResponseRedirect(reverse('personal_management:detail',args = (args['id'], )))
			if 'privilege' in request.POST and act.privilege != int(request.POST['privilege']):
				#用户修改了志愿等级
				if check_privilege_change(request.user, int(request.POST['privilege'])):
					messages.info(request, '志愿修改成功')
					act.privilege = int(request.POST['privilege'])
					act.save()
				else:
					messages.info(request,'您当前志愿已用完')
			return HttpResponseRedirect(reverse('personal_management:detail',args = (args['id'], )))
		elif act.state == custom_model.UNAPPLIED:
			act_content = Activity_Content(request.POST)
			#先进行输入信息有效性的基本检查
			check = valid_check(activity_content = act_content, request = request, time_format = '%Y/%m/%d %H点')
			if not check[0]:
				for msg in check[1]:
					messages.info(request, msg)
				return HttpResponseRedirect(reverse('personal_management:detail',args = (args['id'], )))
			act_content = content_convert(act_content, '%Y/%m/%d %H点')	#转换为有效类型
			if 'apply' in request.POST:
				#进一步进行申请检查
				act_content.id = args['id']; act_content.privilege = int(request.POST['privilege'])
				check = advanced_check(user = request.user, apply = act_content)
				if not check[0]:
					for msg in check[1]:
						messages.info(request, msg)
					return HttpResponseRedirect(reverse('personal_management:detail',args = (args['id'], )))
				else:
					act.state = custom_model.APPLYING
					act.privilege = int(request.POST['privilege'])
					messages.info(request, '已提交活动申请')
			#活动修改加入数据库
			if act_changed(act, act_content):
				messages.info(request, '活动信息修改成功')
			act.name = act_content.name; act.time_start = act_content.time_start;
			act.time_end = act_content.time_end; act.place = act_content.place;
			act.num_participants = act_content.num_participants;
		act.save()
	return HttpResponseRedirect(reverse('personal_management:detail',args = (args['id'], )))


#apply由两个radio构成，是对应1
#文件录入的名字是'file'
@login_required
def load(request, **args):
	type_load = args['type']
	if request.method == 'POST':
		user = request.user
		if len(custom_model.Activity.objects.filter(user = request.user)) >= 100:
			messages.info(request, '你已经上传的活动太多啦QAQ，删一些呗')
			return HttpResponseRedirect(reverse('personal_management:create', args = ('manual', )))
		if type_load == 'manual':
			#手动录入
			dic_act_create = {}
			for key in request.POST:
				dic_act_create[key] = request.POST[key]
			#apply由两个radio构成，是对应1
			dic_act_create['apply'] = True if dic_act_create['apply'] == '1' else False
			dic_act_create['user'] = request.user; dic_act_create['time_format'] = '%Y/%m/%d %H点'
			check = create_activity(**dic_act_create)
			if not check[0]:
				for msg in check[2]:
					messages.info(request, msg)
				return HttpResponseRedirect(reverse('personal_management:create', args = ('manual', )))
			messages.info(request, '活动创建成功')
			check[1].save()
			return HttpResponseRedirect(reverse('personal_management:create', args = ('manual', )))
		elif type_load == 'upload':
			#通过文件上传
			if len(request.FILES) == 0:
				messages.info(request,'还没有上传任何文件哦')
				return HttpResponseRedirect(reverse('personal_management:create', args = ('upload', )))
			else:
				file = request.FILES['file']; line_current = 0
				lst_created = []
				for line in file:
					line_current += 1; p = parse(line)
					if not p[0]:
						messages.info(request, '在第%d行出现了标签解析错误，已撤销录入'%line_current)
						return HttpResponseRedirect(reverse('personal_management:create', args = ('upload', )))
					p[1]['user'] = request.user; p[1]['time_format'] = '%Y/%m/%d/%H'
					check = create_activity(**p[1])
					if not check[0]:
						messages.info(request, '为%d行安排活动时出现错误：'%line_current)
						for msg in check[2]:
							messages.info(request, msg)
						messages.info(request, '已撤销录入')
						return HttpResponseRedirect(reverse('personal_management:create', args = ('upload', )))
					if len(lst_created) > 100:
						messages.info(request, '你已经上传的活动太多啦QAQ，删一些呗')
						messages.info(request, '已撤销录入')
						return HttpResponseRedirect(reverse('personal_management:create', args = ('upload', )))
					lst_created.append(check[1])
				messages.info(request, '活动导入成功')
				for obj in lst_created:
					obj.save()
				return HttpResponseRedirect(reverse('personal_management:create', args = ('upload', )))
	else:
		lst_p = get_privilege_info(request.user)

mysite/personal_management/templates/personal_management/activity_detail.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
	{% load static %}
	{% load p_m_extra_filter %}
	<title>活动详情页</title>
	<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.css'%}"/>
</head>
<body onload="custom_init({{state}}, {{privilege}})">
{%include 'p_m_greetings.html'%}
<div>
	{%include 'p_m_nav.html'%}
	<div id = "main_content" style="float: left;">
		<!--绘制消息-->
		{%include 'p_m_message.html'%}
		<p class="text-info">申请状态：{{state|apply_state}}</p>
		<!--活动编辑-->
		<form role = "form" action="{% url 'personal_management:processor' activity.id %}" method="post" id = "form_detail">
			{% csrf_token %}
			<div id = "div_name" class="form-group">
				<label for="input_name">活动名称</label>
				<input class="form-control" type="text" name="name" value="{{activity.name}}" id="input_name"/>
			</div>
			<div id="div_time_start" class="form-group">
				<label for="input_time_start">起始时间</label>
				<input class="form-control" type="text" name="time_start" value="{{activity.time_start.year}}/{{activity.time_start.month}}/{{activity.time_start.day}} {{activity.time_start.hour}}点" id="input_time_start"/>
				<p class="help-block">输入格式：年/月/日 （24小时制）整点</p>
			</div>
			<div id="div_time_end" class="form-group">
				<label for="input_time_end">结束时间</label>
				<input class="form-control" type="text" name="time_end" value="{{activity.time_end.year}}/{{activity.time_end.month}}/{{activity.time_end.day}} {{activity.time_end.hour}}点" id="input_time_end"/>
				<p class="help-block">输入格式：年/月/日 （24小时制）整点</p>
			</div>
			<div id="div_num_participants" class="form-group">
				<label for="input_num_participants">参与人数</label>
				<input class="form-control" type="number" name="num_participants" value="{{activity.num_participants}}" id="input_num_participants"/>
			</div>
			<div id="div_place" class="form-group">
				<label for="input_place">地点</label>
				<input class="form-control" type="text" name="place" value="{{activity.place}}" id="input_place"/>
			</div>
			<div id="div_privilege", class="form-group">
				<label for="select_privilege">志愿等级</label>
				<select name="privilege" id="select_privilege">
					<option value="0">第一志愿</option>
					<option value="1">第二志愿</option>
					<option value="2">第三志愿</option>
				</select>
				<p>当前志愿情况:第一志愿:{{privilege_info.0}}/{{privilege_bound.0}};第二志愿{{privilege_info.1}}/{{privilege_bound.1}};第三志愿任意
				</p>
			</div>
		<!--撤销按钮-->
			<div class="form-group" id="div_withdraw">
				<label><input id="checkbox_withdraw" type="checkbox" name="withdraw"/>撤销申请</label>
			</div>
			<div class="form-group" id="div_apply">
				<label><input id="checkbox_apply" type="checkbox" name="apply"/>提交申请</label>
			</div>
			<div class="form-group" id="div_delete">
				<label><input id="checkbox_apply" type="checkbox" name="delete"/>删除该活动</label>
			</div>
			<input class="form-control" type="submit" value="确认修改" id="submit_detail">
		</form>
	</div>
	<script type="text/javascript">
		function custom_init(state, privilege) {
			// body...
			var p, children;
			var detail = document.getElementById('form_detail')
			var input_list
			document.getElementById('select_privilege').getElementsByTagName('option')[privilege].setAttribute('selected','selected')
			switch(state)
			{
			case 0:
				//删除撤销申请表单
				detail.removeChild(document.getElementById('div_withdraw'))
				break;
			case 1:
				//删除申请按钮；名称，起始终止时间人数，地点禁用
				detail.removeChild(document.getElementById('div_apply'))
				input_list = detail.getElementsByTagName('div')
				for(var i = 0; i < input_list.length - 1; ++i)
				{
					input_list[i].getElementsByTagName('input')[0].disabled = true
				}
				break;
			default:
				//删除申请按钮和优先级选择按钮，名称，起始终止时间人数，地点禁用
				detail.removeChild(document.getElementById('div_apply'))
				detail.removeChild(document.getElementById('div_privilege'))
				input_list = detail.getElementsByTagName('div')
				for(var i = 0; i < input_list.length - 1; ++i)
				{
					input_list[i].getElementsByTagName('input')[0].disabled = true
				}
				break;
			}
		}
	</script>
</div>
</body>
</html>

mysite/personal_management/templates/personal_management/create.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
	{% load static %}
	{% load p_m_extra_filter %}
	<title>活动导入页面</title>
	<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.css'%}"/>
</head>
<body onload="init_create('{{page_dir}}', '{{type}}')">
{%include 'p_m_greetings.html'%}
<div>
{%include 'p_m_nav.html'%}
<div style="float: left">
	<!--上方导航栏-->
	<div id="nav_search">
		<ul class="nav nav-tabs">
			<li id="nav_create_manual"><a href="{% url 'personal_management:create' 'manual'%}">手动输入</a></li>
			<li id="nav_create_upload"><a href="{% url 'personal_management:create' 'upload'%}">批量导入</a></li>
		</ul>
	</div>
	{%include 'p_m_message.html'%}
	<!--创建活动的表单-->
	<form role="form" action="{{fedback}}" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{%if type == 'manual'%}
		<!--创建手动输入表单-->
		<div id = "div_name" class="form-group">
			<label for="input_name">活动名称</label>
			<input class="form-control" type="text" name="name" value="{{activity.name}}" id="input_name"/>
		</div>
		<div id="div_time_start" class="form-group">
				<label for="input_time_start">起始时间</label>
				<input class="form-control" type="text" name="time_start" id="input_time_start"/>
				<p class="help-block">输入格式：年/月/日 （24小时制）整点</p>
				<p class="help-block">例：2017/7/8 11点（因为date控件在很多浏览器上不支持，所以直接用文本框，不好意思啦）</p>
		</div>
		<div id="div_time_end" class="form-group">
			<label for="input_time_end">结束时间</label>
			<input class="form-control" type="text" name="time_end" id="input_time_end"/>
			<p class="help-block">输入格式：年/月/日 （24小时制）整点</p>
		</div>
		<div id="div_num_participants" class="form-group">
			<label for="input_num_participants">参与人数</label>
			<input class="form-control" type="number" name="num_participants" value="{{activity.num_participants}}" id="input_num_participants"/>
		</div>
		<div id="div_place" class="form-group">
				<label for="input_place">地点</label>
				<input class="form-control" type="text" name="place" value="{{activity.place}}" id="input_place"/>
		</div>
		<!--默认选择第三志愿-->
		<div id="div_privilege", class="form-group">
				<label for="select_privilege">志愿等级</label>
				<select name="privilege" id="select_privilege">
					<option value="0">第一志愿</option>
					<option value="1">第二志愿</option>
					<option value="2" selected="selected">第三志愿</option>
				</select>
				<p>当前志愿情况:第一志愿:{{privilege_info.0}}/{{privilege_bound.0}};第二志愿{{privilege_info.1}}/{{privilege_bound.1}};第三志愿任意
		</div>
		<!--默认不申请-->
		<div id="div_apply" class="form-group">
			<p>是否提出申请</p>
			<input type="radio" name="apply" id="r_a_y" value="1"/>
			<label for="r_a_y">是</label>
			<input type="radio" name="apply" id="r_a_n" value="2" checked="true" />
			<label for="r_a_n">否</label>
		</div>
		{%else%}
		<!--创建文件录入表单-->
		<div class="form-group">
		    <label for="inputfile">文件输入</label>
		    <input class="form-control" type="file" name="file" />
		    <p class="help-block">点击选择您想要录入的文件</p>
		    <p class="help-block">文件格式要求：<br/>每一行对应一条活动。不同的域(按顺序)用标签进行标识：<br/>
		    &lt;name&gt;活动名称(不超过256个字符)&lt;/name&gt;<br/>
		    &lt;time_start&gt;起始时间(年/月/日/整点)(如2017/7/1/16)&lt;/time_start&gt;<br/>
		    &lt;time_end&gt;结束时间(同起始时间，注意当前只支持一天内的活动)&lt;/time_end&gt;<br/>
		    &lt;num_participants&gt;参与人数&lt;/num_participants&gt;<br/>
		    &lt;place&gt;地点&lt;/place&gt;<br/>
		    &lt;privilege&gt;优先级(0,1,2对应1,2,3志愿)&lt;/privilege&gt;<br/>
		    &lt;apply&gt;True表示提交活动申请，其他都视为不申请(建议您在批量录入时尽量少地申请活动，这样有助于提高录入的效率)&lt;/apply&gt;<br/>
		    <b>注意：如果您录入的活动中存在不合适的输入或者提出申请的活动与已经录入的活动产生了冲突，那么文件中的所有活动都不会被录入</b><br/>
		    <p>标签较多，建议直接在这里复制之后粘贴到文件中，去掉所有换行然后输入活动内容
		    </p>
		</div>
		{%endif%}
		<button type="submit" class="btn btn-default">确认</button>
	</form>
</div>
<script type="text/javascript">
	function init_create(pgdir, type_create) {
		// body...
		var type = 'nav_create_' + type_create
		custom_init_nav_side(pgdir)
		document.getElementById(type).className = "active";
	}
</script>
</div>
</body>
</html>

mysite/personal_management/templates/personal_management/detail.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
	{% load static %}
	{% load p_m_extra_filter %}
	<title>List Page</title>
	<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.css'%}"/>
</head>
<body onload="custom_init({{index}})">
<!--acting as a navigator-->
<div id = "side_bar" style="float:left;">
		<p>功能导航</p>
		<ul class="nav nav-pills nav-stacked">
			<li id="a0"><a href="{% url 'personal_management:list_page' 'unapplied'%}">未申请</a></li>
			<li id="a1"><a  href="{%url 'personal_management:list_page' 'applying'%}">正在申请</a></li>
			<li id="a2"><a href="{%url 'personal_management:list_page' 'applied'%}">已申请</a></li>
			<li id="a3"><a href="{%url 'personal_management:search'%}">搜索页面</a></li>
		</ul>
</div>
<div id = "content_main" style = "float: left;" class="container">
	<!--places to check activities, created by template-->
	<div>
		<section>
		<!--activities-->
		{%for act in activity_list%}
			<h2><a href="{% url 'personal_management:detail' act.1.id%}">{{act.1.name}}</a></h2>
			<p style="font-size: 16px">时间：{{act.1.time_start}}至{{act.1.time_end}}</p>
			<p>地点：{{act.1.place}}</p>
		{%endfor%}
		</section>
	</div>
</div>
<script type="text/javascript">
	function custom_init(index) {
		// body...
		str_id = 'a' + index.toString()
		document.getElementById(str_id).className = "active";
	}
</script>
</body>
</html>

mysite/personal_management/templates/personal_management/p_m_greetings.html
<div class="panel panel-primary">
	<div class="panel-heading">
		<h3>欢迎回来：{{username}}</h3>
	</div>
</div>

mysite/personal_management/templates/personal_management/p_m_message.html
{% if messages %}
<div class="alert alert-info messages" role="alert">
<ul class="messages list-unstyled">
{% for message in messages %}
<li{% if message.tags %} class="{{ message.tags}}" {% endif %}>
{{ message }}
</li>
{% endfor %}
</ul>
</div>
{% endif %}

mysite/personal_management/templates/personal_management/p_m_nav.html
<div id = "side_bar" style="float:left;">
		<p>功能导航</p>
		<ul class="nav nav-pills nav-stacked">
			<li id="nav_sidebar0"><a href="{% url 'personal_management:list_page' 'unapplied'%}">未申请</a></li>
			<li id="nav_sidebar1"><a  href="{%url 'personal_management:list_page' 'applying'%}">正在申请</a></li>
			<li id="nav_sidebar2"><a href="{%url 'personal_management:list_page' 'applied'%}">已申请</a></li>
			<li id="nav_sidebar3"><a href="{%url 'personal_management:search' 'time'%}">搜索页面</a></li>
			<li id="nav_sidebar5"><a href="{%url 'personal_management:create' 'manual'%}">活动录入</a></li>
			<li id="nav_sidebar4"><a href="{%url 'display'%}">申请结果公示</a></li>
			<li id="nav_sidebar6"><a href="{%url 'personal_management:log_out'%}">登出</a></li>
		</ul>
</div>
<script type="text/javascript">
	function custom_init_nav_side(index) {
		// body...
		str_id = 'nav_sidebar' + index.toString()
		document.getElementById(str_id).className = "active";
	}
</script>

mysite/personal_management/templates/personal_management/script_test.html
<!DOCTYPE html>
<html>
<head>
	<title>hello</title>
</head>
<body onload="custom_init()">
<div id = "div_test">
	<p id="para_test">this is a paragraph</p>
	<p>this is another paragraph</p>
</div>
<p id = "para">old</p>
<p><a href="http://www.baidu.com" style="background-color: #00FF00">ts</a>about</p>
<script type="text/javascript">
	function custom_init()
	{
		/*
		var str = ''
		str += 'hello';
		num = 0;
		str += num.toString()
		var old =  document.getElementById("para");
		old.innerHTML = str;
		*/
		var p = document.getElementById('div_test')
		p.removeChild(p.getElementsByTagName('p')[2])
	}
</script>
<!--
<form role = "form" action="{% url 'personal_management:processor' activity.id %}" method="post" id = "form_detail">
	<div id = "div_name">
		<label for="input_name">活动名称</label>
		<input type="text" name="name" value="{{act.name}}" id="input_name"/>
	</div>
	<div id="div_time_start">
		<label for="input_time_start">起始时间</label>
		<input type="text" name="time_start" value="{{act.time_start}}" id="input_time_start"/>
	</div>
	<div id="div_time_end">
		<label for="input_time_end">结束时间</label>
		<input type="text" name="time_end" value="{{act.time_end}}" id="input_time_end"/>
	</div>
	<div id="div_num_participants">
		<label for="input_num_participants">起始时间</label>
		<input type="number" name="num_participants" value="{{act.num_participants}}" id="input_num_participants"/>
	</div>
	<div id="div_place">
		<label for="input_place">地点</label>
		<input type="text" name="place" value="{{act.place}}" id="input_place"/>
	</div>
	<input type="submit" value="确认修改" id="submit_detail">
</form>
-->

</body>
</html>