mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings 
from django.conf.urls.static import static
from django.views.static import serve
urlpatterns = [
	url(r'^user/', include('personal_management.urls')),	#redirected to user page
	url(r'^manager/', include('manager.urls')),
	url(r'^result/', include('act_result.urls')),
    url(r'^admin/', admin.site.urls),
	url(r'^welcome/', include('start.urls')),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT})
]
'''
if settings.DEBUG is False:
    urlpatterns += patterns('', url(r'^static/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.STATIC_ROOT, }), )
'''

mysite/personal_management/urls.py
from django.conf.urls import url
from . import views

app_name = 'personal_management'
urlpatterns = [
	url(r'^fake_log_in$', views.fake_log_in, name = 'f_log_in'),
	url(r'^fake_log_out$', views.fake_log_out, name = 'f_log_out'),
	url(r'^list_page/(?P<content>applied|unapplied|applying)/$',\
	views.list_page , name = 'list_page'),
	url(r'^search/(?P<type>time|place|name)$', views.search, name = 'search'),
	url(r'^activity_detail/(?P<id>[0-9]+)$', views.detail, name = 'detail'),
	url(r'^edit_processor/(?P<id>[0-9]+)$', views.processor, name = 'processor'),
	url(r'^widthdraw$', views.withdraw, name = 'withdraw'),
	url(r'^apply$', views.apply, name = 'apply'),
	url(r'^create/(?P<type>manual|upload)', views.load, name = 'create'),
	url(r'^refresh/$', views.profile_refresh, name = 'refresh'),
	url(r'^log_out/$', views.my_log_out, name = 'log_out'),
]

mysite/start/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.start, name = 'start'),
	url(r'^help$', views.help, name = 'help'),
]

mysite/start/models.py
from django.db import models

# Create your models here.

mysite/start/views.py
from django.shortcuts import render

# Create your views here.
def start(request):
	return render(request, "start.html")

def help(request):
	return render(request, "help.html")

mysite/start/templates/base.html
<!DOCTYPE html>
<html><head>
    <meta charset="utf-8">
    <title>活动管家</title>
    {% load static %}
	    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" type="text/css">
    </head><body>
    <div class="container">
	    <div class="header clearfix"><h3 class="text-muted">活动管家</h3></div>
	{% if messages %}
		<ul class="messages">
			{% for message in messages %}
				<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
			{% endfor %}
		</ul>
	{% endif %}
    <section id="content">{% block content %}{% endblock %}</section>
    <footer class="footer"><p>&copy; 2017 活动管家</p></footer>
</div>
</body></html>

mysite/start/templates/help.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
<div>
本网站用于模拟用户根据对应的地点进行活动安排，与其他用户竞争有限的课室资源的情景（类似选课）
<h3>用户可以做什么？</h3>
	<p>
		<h4>1、地点查询（无需登录）</h4>
		查询已经有的地点，根据这些创建好的地点进行活动的选择
		<p><font color="red">操作位置：首页-活动安排表，下方有按名字搜索地点的搜索栏</font></p>
	</p>
	<p>
		<h4>2、活动的创建、申请和导入</h4>
		用户可以选择手动创建自己的活动或者使用文件导入，之后可以进行申请。申请时不能和已经被安排的活动冲突，要在地点规定的时间范围和人数范围内，并且有一定数量的志愿
		<p><font color="red">操作位置：登录后自动跳转到用户界面，点击边栏即可进行切换</font></p>
	</p>
	<p>
		<h4>3、总体活动安排查询（无需登录）</h4>
		可以看到教室当前的活动安排情况和每个时段的申请人数
		<p><font color="red">操作位置：首页-活动安排表，先搜索对应的地点之后再根据需要的时间段进行搜索</font></p>
	</p>
<h3>管理员会做什么？</h3>
	<p>1、提前导入地点和地点对应的信息</p>
	<p>2、进行验证码的导入</p>
	<p>3、手动进行活动的安排</p>
</div>

	<div>
		<a href="{% url 'start' %}">
			<button class="btn btn-lg">
				返回主页
			</button>
		</a>
	</div>
{% endblock %}

mysite/start/templates/start.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

<div class="text-align:center">
	<h2 style="text-align:center">您好！欢迎进入活动安排网站“活动管家”的引导页面</h2>
</div>
<br />
<div class="col-sm-6, col-md-6" style="text-align:center">
	<div style="font-size:24px">
		如果您有一个账号？
	</div>
	<br />	
	<div>
		<a href="{% url 'login' %}">
			<button class="btn btn-lg">
				登录
			</button>
		</a>
	</div>
	
	<br />	
	<br />
	<br />
	
	<div style="font-size:24px">
		如果您没有账号但是有验证码？
	</div>
	<br />
	<div>
	<a href="{% url 'regist' %}">
		<button class="btn btn-lg">
			注册
		</button>
	</a>
	</div>

</div>

<div class="col-sm-6, col-md-6" style="text-align:center">
	<div style="font-size:24px">
		如果您需要浏览当前的活动安排列表？
	</div>
	<br />	
	<div>
		<a href="{% url 'display' %}">
			<button class="btn btn-lg">
				活动安排表
			</button>
		</a>
	</div>
	
	<br />	
	<br />
	<br />
	
	<div style="font-size:24px">
		如果您还有什么不明白的？
	</div>
	<br />
	<div>
	<a href="{% url 'help' %}">
		<button class="btn btn-lg">
			帮助文档
		</button>
	</a>
	</div>

</div>



<div style="text-align:center">

	<div style="font-size:24px">
		如果您已经登录了，并想查看自己的活动？
	</div>
	<br />
	<div>
		<a href="{% url 'personal_management:list_page' 'unapplied' %}">
			<button class="btn btn-lg">
				个人中心
			</button>
		</a>
	</div>
</div>

{%endblock%}